---
# Type

- name: 'Type: Bug'
  color: b82c17
  description: "The project isn't doing what it should correctly."
- name: 'Type: Security'
  color: b80083
  description: 'Vulnerability or security risk.'
- name: 'Type: Feature'
  color: 7f00ff
  description: 'New functionality.'
- name: 'Type: Documentation'
  color: 0000ff
  description: 'In-project documentation, both doc files and code comments.'
- name: 'Type: Question'
  color: 80ff00
  description:
    'Requests for help on how to use the project, or general questions.'
- name: 'Type: Build'
  color: 555555
  description: 'Change in the project build process, including GitHub Actions.'
- name: 'Type: Chore'
  color: 555555
  description: 'Generic maintenance tasks.'

# Status

- name: 'Status: Available'
  color: bee4be
  description: 'Not currently being worked on. Take the lead!'
- name: 'Status: In Progress'
  color: fef2c0
  description: 'Work is underway.'
- name: 'Status: Update Needed'
  color: e11d21
  description: 'Missing necessary information or review.'
- name: 'Status: Blocked or Postponed'
  color: 006a74
  description: 'On hold.'
- name: 'Status: Done'
  color: 000000
  description: 'Completed.'
- name: "Status: Won't Fix"
  color: cdcdcd
  description:
    'Outside project scope, off-topic, spam, or otherwise does not apply to this
    project.'

# Priority

- name: 'Priority: Critical'
  color: e11c20
- name: 'Priority: High'
  color: eb6420
- name: 'Priority: Medium'
  color: fbca04
- name: 'Priority: Low'
  color: 84b6ea

# Welcome

- name: 'good first issue'
  color: 2da44e
  description:
    'Beginner-friendly issue for people wanting to contribute to this project.'
- name: 'help wanted'
  color: 2da44e
  description:
    'We need some extra helping hands or expertise in order to resolve this!'
