name: Check accessibility (axe)
on:
  push:
    branches:
      # Build whenever the main branch is pushed.
      - 'main'
  pull_request:
    branches:
      # Build whenever the main branch has a pull request.
      - 'main'
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm start & npx wait-on http://localhost:9050
      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          axe http://localhost:9050 --exit
