name: Build and publish to GitHub Pages branch

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '.github/**'

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - name: Build the production site
        run: |
          gulp prod
      - name: Publish to the GitHub Pages branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: site # The branch name where you want to push the assets
          FOLDER: build # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: 'Build: ({sha}) {msg}' # The commit message
