name: Build and publish to GitHub Pages branch

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '.github/**'

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup repo
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - name: Build the production site
        run: |
          gulp prod
      - name: Publish to the GitHub Pages branch
        env:
          SRC_FOLDER_PATH: 'build'
          TARGET_BRANCH: 'site'
        run: |
          files=$(find $SRC_FOLDER_PATH -type f)
          git fetch
          git checkout $TARGET_BRANCH
          git checkout ${GITHUB_REF##*/} -- $files
          git add -A
          git diff-index --quiet HEAD || git commit -am "Publish site"
          git push origin $TARGET_BRANCH
