name: Check accessibility (a11y)
on:
  push:
    branches:
      # Build whenever the main branch is pushed.
      - 'main'
  branches:
    # Build whenever the main branch has a pull request.
    - 'main'
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm start & npx wait-on http://localhost:9050
      - name: Run pa11y
        run: |
          npm install -g pa11y
          pa11y http://localhost:9050
